SIDDHANT SINHA

25070123109

Unit-3 Data Wrangling

Experiment-13

To perform preprocessing on a dataset and Dealing with Missing Values

In [4]:
import pandas as pd
import numpy as np

#np.nan for missing values........NaN means not a number
#pd.DataFrame converts it into tabular form

df1=pd.DataFrame({'C1':[11,21, np.nan],'C2':[15, np.nan, np.nan],'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [5]:
#To find where is nan
df1.isna()          #Boolean function isna

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [6]:
df1.notna()         #this shows NaN as false

      C1     C2    C3
0   True   True  True
1   True  False  True
2  False  False  True

In [7]:
df1.isna().sum()                                 #tells the number of null values/ NaN in columns

C1    1
C2    2
C3    0
dtype: int64

In [8]:
df1.isna().sum(axis=1)                           #same thing if we want of row.......axis=1 is rows axis=0 is columns

0    0
1    1
2    2
dtype: int64

In [9]:
#DATA CLEANING BY DELETING ROWS

df1.dropna()     #NaN Rows are dropped....here axis=0 rows and axis=1 columns

     C1    C2  C3
0  11.0  15.0  10

In [10]:
#DATA CLEANING BY DELETING COLUMNS

df1.dropna(axis=1)     #NaN Columns are dropped

   C3
0  10
1  20
2  30

In [11]:
df1.fillna(value='DEFAULT')        #changes NaN to DEFAULT

        C1       C2  C3
0     11.0     15.0  10
1     21.0  DEFAULT  20
2  DEFAULT  DEFAULT  30

In [12]:
df1.fillna(0)                 # replaced with zero

     C1    C2  C3
0  11.0  15.0  10
1  21.0   0.0  20
2   0.0   0.0  30

In [13]:
df1.fillna(df1.mean())                #replaced by (mean) column wise

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [14]:
#Preprocesing of datasheet 1

import pandas as pd

data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Asha", "Rohan", "Meera", "Karan", "Anil"],
    "Age": [20, "-", 21, 20, "22"],
    "Marks": [85, 90, "-", 88, 76],
    "Department": ["CSE", "IT", "CSE", "cse", "E&TC"],
    "Admission_Date": ["01-06-2023", "03-06-2023", "05-06-2023", "07-06-2023", "10/06/23"]
}

df = pd.DataFrame(data)
df

   Roll No   Name Age Marks Department Admission_Date
0      101   Asha  20    85        CSE     01-06-2023
1      102  Rohan   -    90         IT     03-06-2023
2      103  Meera  21     -        CSE     05-06-2023
3      104  Karan  20    88        cse     07-06-2023
4      105   Anil  22    76       E&TC       10/06/23

In [15]:
#Replacing '-' with NaN


df.replace("-", np.nan, inplace= True)                #inplace= True replaces the old table with new one
df

/tmp/ipykernel_15015/2685636498.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-", np.nan, inplace= True)                #inplace= True replaces the old table with new one

   Roll No   Name  Age  Marks Department Admission_Date
0      101   Asha   20   85.0        CSE     01-06-2023
1      102  Rohan  NaN   90.0         IT     03-06-2023
2      103  Meera   21    NaN        CSE     05-06-2023
3      104  Karan   20   88.0        cse     07-06-2023
4      105   Anil   22   76.0       E&TC       10/06/23

In [16]:
# as age will be more likely same and student will not have much variation in age so we replace it by "MEAN"
# marks has more variation so replace by "MEDIAN"
# "MODE" is used like if categorical data is there such as department

df.replace("-", np.nan, inplace= True)

#CONVERT COLUMNS TO NUMERIC WHERE NEEDED

df["Age"]= pd.to_numeric(df["Age"],errors='coerce')
df["Marks"]= pd.to_numeric(df["Marks"],errors='coerce')
df

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan   NaN   90.0         IT     03-06-2023
2      103  Meera  21.0    NaN        CSE     05-06-2023
3      104  Karan  20.0   88.0        cse     07-06-2023
4      105   Anil  22.0   76.0       E&TC       10/06/23

In [17]:
# as age will be more likely same and student will not have much variation in age so we replace it by "MEAN"
# marks has more variation so replace by "MEDIAN"
# "MODE" is used like if categorical data is there such as department

#df.replace("-", np.nan, inplace= True)

#CONVERT COLUMNS TO NUMERIC WHERE NEEDED

df["Age"]= pd.to_numeric(df["Age"],errors='coerce')
df["Marks"]= pd.to_numeric(df["Marks"],errors='coerce')
df

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan   NaN   90.0         IT     03-06-2023
2      103  Meera  21.0    NaN        CSE     05-06-2023
3      104  Karan  20.0   88.0        cse     07-06-2023
4      105   Anil  22.0   76.0       E&TC       10/06/23

In [18]:
#Fill missing age with mean and marks with median

df["Age"].fillna(df["Age"].mean(), inplace=True)
df["Marks"].fillna(df["Marks"].median(), inplace=True)
df

/tmp/ipykernel_15015/3331429804.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].mean(), inplace=True)
/tmp/ipykernel_15015/3331429804.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Marks"].fillna(df["Marks"].median(), inplace=True)

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00   86.5        CSE     05-06-2023
3      104  Karan  20.00   88.0        cse     07-06-2023
4      105   Anil  22.00   76.0       E&TC       10/06/23

In [19]:
#changing small department to upper or capital letter

df["Department"]=df["Department"].str.upper()
df

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00   86.5        CSE     05-06-2023
3      104  Karan  20.00   88.0        CSE     07-06-2023
4      105   Anil  22.00   76.0       E&TC       10/06/23

In [20]:
# changing date to a same format
#df["Admission_Date"]= pd.to_datetime(df["Admission_Date"], errors='coerce') also true but does not work on colab
df["Admission_Date"]= pd.to_datetime(df["Admission_Date"], format="mixed", dayfirst=True)
(df)

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     2023-06-01
1      102  Rohan  20.75   90.0         IT     2023-06-03
2      103  Meera  21.00   86.5        CSE     2023-06-05
3      104  Karan  20.00   88.0        CSE     2023-06-07
4      105   Anil  22.00   76.0       E&TC     2023-06-10

In [21]:
# changing date to a same format
#df["Admission_Date"]= pd.to_datetime(df["Admission_Date"], errors='coerce') also true but does not work on colab
df["Admission_Date"]= pd.to_datetime(df["Admission_Date"], format="mixed", dayfirst=True)
display(df)

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     2023-06-01
1      102  Rohan  20.75   90.0         IT     2023-06-03
2      103  Meera  21.00   86.5        CSE     2023-06-05
3      104  Karan  20.00   88.0        CSE     2023-06-07
4      105   Anil  22.00   76.0       E&TC     2023-06-10